### ISSUE TITLE
Feature list of this repo

### ISSUE THREAD

**Issue by ondics** [vrk-kpa/ckanext-matomo#2]
Hi, great idea to support matomo for ckan. thank you for your efforts.
While working with matomo with lots of websites there is always just a little snippet to integrate in the website. 
And there is mostly just one number (`site_id`) to be configured.
This repo seems to provide more.  
It would be great to provide a detailed list of features in your readme.

**Comment by Zharktas** [comment]
We'll add comprehensive documentation. The features are mostly ported from ckanext-googleanalytics.

**Comment by ondics** [comment]
Thank you. Great,
