### ISSUE TITLE
Helper 'check_ckan_version' has not been defined

### ISSUE THREAD

**Issue by 4estone** [vrk-kpa/ckanext-matomo#34]
I get this error when running my skan instance with matomo extension
Ckan version : 2.9.3

File "/usr/lib/ckan/default/src/ckanext-matomo/ckanext/matomo/plugin/../templates/base.html", line 10, in block "scripts"
Jun 07 09:48:52 T-ODATA-1 uwsgi[4312]: {% block matomo_event_tracking %}
Jun 07 09:48:52 T-ODATA-1 uwsgi[4312]: File "/usr/lib/ckan/default/src/ckanext-matomo/ckanext/matomo/plugin/../templates/base.html", line 11, in block "matomo_event_tracking"
Jun 07 09:48:52 T-ODATA-1 uwsgi[4312]: {% set type = 'asset' if h.check_ckan_version(min_version="2.9.0", max_version="3.0.0") else 'resource' %}
Jun 07 09:48:52 T-ODATA-1 uwsgi[4312]: File "/usr/lib/ckan/default/lib64/python3.6/site-packages/jinja2/environment.py", line 434, in getattr
Jun 07 09:48:52 T-ODATA-1 uwsgi[4312]: return obj[attribute]
Jun 07 09:48:52 T-ODATA-1 uwsgi[4312]: File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 101, in __getitem__
Jun 07 09:48:52 T-ODATA-1 uwsgi[4312]: key=key
Jun 07 09:48:52 T-ODATA-1 uwsgi[4312]: ckan.exceptions.HelperError: Helper 'check_ckan_version' has not been defined.

**Comment by Zharktas** [comment]
You should update your ckan, the helper is available in ckan 2.9.6 https://github.com/ckan/ckan/pull/6741
